# Generated by Django 5.0.6 on 2024-07-06 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='number_of_views',
        ),
        migrations.AddField(
            model_name='movie',
            name='Description',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
